[package]
name = "src"
version = "0.1.0"
cairo-version = "2.8.4"

[dependencies]
starknet = "2.8.4"

[dev-dependencies]
cairo_test = "2.8.4"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest